#!/bin/bash
# Build a Solar2D project for HTML5 (WebAssembly)
#
# Usage (Docker):
#   docker run -v $(pwd)/corona:/project -v $(pwd)/out:/output solar2d build --app-name MyApp
#
# Environment variables (alternative to flags):
#   PROJECT_PATH  - Path to Solar2D project (default: /project)
#   OUTPUT_PATH   - Build output directory (default: /output)
#   APP_NAME      - Application name (required)
#   APP_VERSION   - Application version (default: 1.0.0)

set -euo pipefail

# Defaults
PROJECT_PATH="${PROJECT_PATH:-/project}"
OUTPUT_PATH="${OUTPUT_PATH:-/output}"
APP_NAME="${APP_NAME:-}"
APP_VERSION="${APP_VERSION:-1.0.0}"
SOLAR2D_BUILDER="${SOLAR2D_BUILDER:-Solar2DBuilder}"
WEBTEMPLATE="${WEBTEMPLATE:-/usr/local/share/solar2d/Resources/webtemplate.zip}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --project-path) PROJECT_PATH="$2"; shift 2 ;;
        --output-path)  OUTPUT_PATH="$2"; shift 2 ;;
        --app-name)     APP_NAME="$2"; shift 2 ;;
        --app-version)  APP_VERSION="$2"; shift 2 ;;
        --webtemplate)  WEBTEMPLATE="$2"; shift 2 ;;
        --builder)      SOLAR2D_BUILDER="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Check for custom webtemplate directory and create custom webtemplate if it exists
CUSTOM_WEBTEMPLATE_DIR="/html5-custom"
FINAL_WEBTEMPLATE="$WEBTEMPLATE"

if [ -d "$CUSTOM_WEBTEMPLATE_DIR" ]; then
    echo "Found custom webtemplate directory, creating custom webtemplate..."
    FINAL_WEBTEMPLATE="/tmp/custom-webtemplate.zip"
    cp "$WEBTEMPLATE" "$FINAL_WEBTEMPLATE"
    # Add custom files under html/ prefix (what Solar2D expects)
    OVERLAY=$(mktemp -d)
    ln -s "$CUSTOM_WEBTEMPLATE_DIR" "$OVERLAY/html"
    (cd "$OVERLAY" && zip -r "$FINAL_WEBTEMPLATE" html/)
    rm -rf "$OVERLAY"
    echo "  Created custom webtemplate at $FINAL_WEBTEMPLATE"
fi

echo "=== Solar2D HTML5 Build ==="
echo "  Project:     $PROJECT_PATH"
echo "  Output:      $OUTPUT_PATH"
echo "  App Name:    $APP_NAME"
echo "  App Version: $APP_VERSION"
echo "  Template:    $FINAL_WEBTEMPLATE"
echo ""

# Create output directory
mkdir -p "$OUTPUT_PATH"

# Generate build params Lua file
PARAMS_FILE=$(mktemp /tmp/html5_build_params_XXXXXX.lua)
cat > "$PARAMS_FILE" <<LUA
local params =
{
    platform = 'html5',
    appName = '$APP_NAME',
    appVersion = '$APP_VERSION',
    dstPath = '$OUTPUT_PATH',
    projectPath = '$PROJECT_PATH',
    webtemplate = '$FINAL_WEBTEMPLATE',
}
return params
LUA

echo "Build params:"
cat "$PARAMS_FILE"
echo ""

# BUILD_VERSION is passed from CI. Default to "dev" for local builds.
BUILD_VERSION="${BUILD_VERSION:-dev}"

# Inject _G.BUILD_VERSION into Lua
VERSION_FILE="$PROJECT_PATH/version.lua"
VERSION_EXISTED=false
if [ -f "$VERSION_FILE" ]; then VERSION_EXISTED=true; fi
cat > "$VERSION_FILE" <<VERLUA
-- Auto-generated by build-html5.sh — do not edit
_G.BUILD_VERSION = "${BUILD_VERSION}"
VERLUA
echo "Injected build version: ${BUILD_VERSION}"

# Run the build
echo "Starting Solar2DBuilder..."
"$SOLAR2D_BUILDER" build --lua "$PARAMS_FILE"

# A custom index.html may carry a __SENTRY_RELEASE__ placeholder; fill it in when
# the caller says what the release is. Nothing happens if they do not.
OUTPUT_INDEX="$OUTPUT_PATH/$APP_NAME.html5/index.html"
if [ -n "${SENTRY_RELEASE:-}" ] && [ -f "$OUTPUT_INDEX" ]; then
    sed -i "s|__SENTRY_RELEASE__|${SENTRY_RELEASE}|g" "$OUTPUT_INDEX"
    echo "Injected Sentry release: ${SENTRY_RELEASE}"
fi

# Clean up injected version file if it didn't exist before
if [ "$VERSION_EXISTED" = false ] && [ -f "$VERSION_FILE" ]; then
    rm -f "$VERSION_FILE"
fi

# Clean up
rm -f "$PARAMS_FILE"
if [ -f "$FINAL_WEBTEMPLATE" ] && [ "$FINAL_WEBTEMPLATE" != "$WEBTEMPLATE" ]; then
    rm -f "$FINAL_WEBTEMPLATE"
fi

echo ""
echo "=== Build Successful ==="
echo "Output files:"
ls -lh "$OUTPUT_PATH/$APP_NAME.html5"
