#!/bin/bash
# Build a Solar2D project for Android (APK + AAB)
#
# Usage (Docker):
#   docker run -v $(pwd)/corona:/project -v $(pwd)/out:/output solar2d build-android --app-name MyApp --package com.example.myapp
#
# Environment variables (alternative to flags):
#   PROJECT_PATH        - Path to Solar2D project (default: /project)
#   OUTPUT_PATH         - Build output directory (default: /output)
#   APP_NAME            - Application name (required)
#   APP_VERSION         - versionName shown to users (default: 1.0.0)
#   ANDROID_PACKAGE     - Application id, e.g. com.example.myapp (required)
#   ANDROID_VERSION_CODE- Integer versionCode (default: 1)
#   ANDROID_STORE       - google | amazon | none (default: google)
#
# Signing (all optional — without them the build is signed with Android's public
# debug key and can be installed but not distributed):
#   ANDROID_KEYSTORE        - Path to a .keystore/.jks file
#   ANDROID_KEYSTORE_BASE64 - ...or the same file base64-encoded, for CI secrets
#   ANDROID_KEYSTORE_PASSWORD
#   ANDROID_KEYSTORE_ALIAS
#   ANDROID_KEYSTORE_ALIAS_PASSWORD

set -euo pipefail

# Defaults
PROJECT_PATH="${PROJECT_PATH:-/project}"
OUTPUT_PATH="${OUTPUT_PATH:-/output}"
APP_NAME="${APP_NAME:-}"
APP_VERSION="${APP_VERSION:-1.0.0}"
ANDROID_PACKAGE="${ANDROID_PACKAGE:-}"
ANDROID_VERSION_CODE="${ANDROID_VERSION_CODE:-1}"
ANDROID_STORE="${ANDROID_STORE:-google}"
ANDROID_KEYSTORE="${ANDROID_KEYSTORE:-}"
ANDROID_KEYSTORE_BASE64="${ANDROID_KEYSTORE_BASE64:-}"
ANDROID_KEYSTORE_PASSWORD="${ANDROID_KEYSTORE_PASSWORD:-}"
ANDROID_KEYSTORE_ALIAS="${ANDROID_KEYSTORE_ALIAS:-}"
ANDROID_KEYSTORE_ALIAS_PASSWORD="${ANDROID_KEYSTORE_ALIAS_PASSWORD:-}"
SOLAR2D_BUILDER="${SOLAR2D_BUILDER:-Solar2DBuilder}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --project-path)    PROJECT_PATH="$2"; shift 2 ;;
        --output-path)     OUTPUT_PATH="$2"; shift 2 ;;
        --app-name)        APP_NAME="$2"; shift 2 ;;
        --app-version)     APP_VERSION="$2"; shift 2 ;;
        --package)         ANDROID_PACKAGE="$2"; shift 2 ;;
        --version-code)    ANDROID_VERSION_CODE="$2"; shift 2 ;;
        --store)           ANDROID_STORE="$2"; shift 2 ;;
        --keystore)        ANDROID_KEYSTORE="$2"; shift 2 ;;
        --builder)         SOLAR2D_BUILDER="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ -z "$APP_NAME" ]; then
    echo "ERROR: --app-name is required" >&2
    exit 1
fi
if [ -z "$ANDROID_PACKAGE" ]; then
    echo "ERROR: --package (or ANDROID_PACKAGE) is required" >&2
    exit 1
fi
case "$ANDROID_VERSION_CODE" in
    ''|*[!0-9]*) echo "ERROR: version code must be an integer, got '$ANDROID_VERSION_CODE'" >&2; exit 1 ;;
esac

# Everything secret this script writes goes in here, and it is removed however the
# script exits: the params file below holds the keystore password in clear text
# because that is the only way CoronaBuilder accepts it.
WORK_DIR=$(mktemp -d /tmp/android_build_XXXXXX)
chmod 700 "$WORK_DIR"
cleanup() {
    rm -rf "$WORK_DIR"
    if [ "${VERSION_EXISTED:-false}" = false ] && [ -n "${VERSION_FILE:-}" ] && [ -f "$VERSION_FILE" ]; then
        rm -f "$VERSION_FILE"
    fi
}
trap cleanup EXIT

# A keystore handed over as base64 (how CI secrets travel) is materialised here.
if [ -n "$ANDROID_KEYSTORE_BASE64" ] && [ -z "$ANDROID_KEYSTORE" ]; then
    ANDROID_KEYSTORE="$WORK_DIR/release.keystore"
    echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > "$ANDROID_KEYSTORE"
    echo "Decoded keystore from ANDROID_KEYSTORE_BASE64"
fi

SIGNING="release"
if [ -z "$ANDROID_KEYSTORE" ]; then
    SIGNING="debug"
elif [ ! -f "$ANDROID_KEYSTORE" ]; then
    echo "ERROR: keystore not found: $ANDROID_KEYSTORE" >&2
    exit 1
fi

echo "=== Solar2D Android Build ==="
echo "  Project:      $PROJECT_PATH"
echo "  Output:       $OUTPUT_PATH"
echo "  App Name:     $APP_NAME"
echo "  App Version:  $APP_VERSION"
echo "  Package:      $ANDROID_PACKAGE"
echo "  Version Code: $ANDROID_VERSION_CODE"
echo "  Store:        $ANDROID_STORE"
echo "  Signing:      $SIGNING"
if [ "$SIGNING" = "debug" ]; then
    echo ""
    echo "  WARNING: no keystore supplied. The build is signed with Android's public"
    echo "  debug key — installable for testing, rejected by Play and by Firebase App"
    echo "  Distribution's Play-linked flows. Set ANDROID_KEYSTORE_BASE64 to sign for real."
fi
echo ""

mkdir -p "$OUTPUT_PATH"

# BUILD_VERSION is passed from CI. Default to "dev" for local builds.
BUILD_VERSION="${BUILD_VERSION:-dev}"

# Inject _G.BUILD_VERSION into Lua (same contract as build-html5.sh)
VERSION_FILE="$PROJECT_PATH/version.lua"
VERSION_EXISTED=false
if [ -f "$VERSION_FILE" ]; then VERSION_EXISTED=true; fi
cat > "$VERSION_FILE" <<VERLUA
-- Auto-generated by build-android.sh — do not edit
_G.BUILD_VERSION = "${BUILD_VERSION}"
VERLUA
echo "Injected build version: ${BUILD_VERSION}"

# Generate build params Lua file.
# 'certificatePath' is CoronaBuilder's name for the keystore; supplying it is also
# what flips the build from debug- to release-signed, which is why the password
# fields are only written alongside it.
PARAMS_FILE="$WORK_DIR/params.lua"
{
    echo "local params ="
    echo "{"
    echo "    platform = 'android',"
    echo "    appName = [==[$APP_NAME]==],"
    echo "    appVersion = [==[$APP_VERSION]==],"
    echo "    dstPath = [==[$OUTPUT_PATH]==],"
    echo "    projectPath = [==[$PROJECT_PATH]==],"
    echo "    androidAppPackage = [==[$ANDROID_PACKAGE]==],"
    echo "    androidVersionCode = $ANDROID_VERSION_CODE,"
    echo "    androidStore = [==[$ANDROID_STORE]==],"
    if [ "$SIGNING" = "release" ]; then
        echo "    certificatePath = [==[$ANDROID_KEYSTORE]==],"
        echo "    keystorePassword = [==[$ANDROID_KEYSTORE_PASSWORD]==],"
        echo "    keystoreAlias = [==[$ANDROID_KEYSTORE_ALIAS]==],"
        echo "    keystoreAliasPassword = [==[$ANDROID_KEYSTORE_ALIAS_PASSWORD]==],"
    fi
    echo "}"
    echo "return params"
} > "$PARAMS_FILE"
chmod 600 "$PARAMS_FILE"

# Deliberately not `cat "$PARAMS_FILE"` the way the HTML5 build does — the file has
# the keystore passwords in it, and CI logs are not a place for those.
echo "Build params written (contents withheld: file carries signing secrets)"
echo ""

echo "Starting Solar2DBuilder..."
"$SOLAR2D_BUILDER" build --lua "$PARAMS_FILE"

APK="$OUTPUT_PATH/$APP_NAME.apk"
AAB="$OUTPUT_PATH/$APP_NAME.aab"
if [ ! -f "$APK" ] && [ ! -f "$AAB" ]; then
    echo "ERROR: build reported success but produced neither $APK nor $AAB" >&2
    exit 1
fi

echo ""
echo "=== Build Successful ==="
echo "Output files:"
ls -lh "$OUTPUT_PATH"
